version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gosec
    - testpackage
    - wrapcheck
    - wsl
  exclusions:
    presets:
      - comments
run:
  timeout: 2m
  tests: true
